spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql:///literature?characterEncoding=UTF-8&useSSL=false
    username: root
    password: 950920
  servlet:
    multipart: #设置上传文件大小
      max-file-size: 50MB
      max-request-size: 50MB
  mvc:
    static-path-pattern: /**
    resources:
      static-locations:
        - classpath:/META-INF/resources/
        - classpath:/static
        - classpath:/resources/
        - file:${upload-path}
  upload-path: D:/head/

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 9999
